{
  "formatVersion": "1.1",
  "component": {
    "group": "name.project.mona.sdk",
    "module": "core",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.doyaaaaaken",
          "module": "kotlin-csv-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-sdk-services",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-sdk-core",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-sdk-geojson",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "com.mapbox.navigation",
          "module": "android",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.quickbirdstudios",
          "module": "opencv",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-gpu",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-gpu-api",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-support",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.1.aar",
          "url": "core-0.0.1.aar",
          "size": 69379498,
          "sha512": "733218417a5b92251501b50da359c93d3b61b819cb5362911b4b8be9087b257ba113e26bff4a620161cf33182ba95c70c9300576005430ca43d89a78035d796c",
          "sha256": "57e6ea9d23be033ec42bfde594d1274227d59c76f3fdc280b88c50fba5edcc8c",
          "sha1": "2680efd4be7c0f393a40d0c4f2edd171326a320a",
          "md5": "f15d3f37430bfe4e950dfa8462edadb8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.doyaaaaaken",
          "module": "kotlin-csv-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-sdk-services",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-sdk-core",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "com.mapbox.mapboxsdk",
          "module": "mapbox-sdk-geojson",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "com.mapbox.navigation",
          "module": "android",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.quickbirdstudios",
          "module": "opencv",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-gpu",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-gpu-api",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-support",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.1.aar",
          "url": "core-0.0.1.aar",
          "size": 69379498,
          "sha512": "733218417a5b92251501b50da359c93d3b61b819cb5362911b4b8be9087b257ba113e26bff4a620161cf33182ba95c70c9300576005430ca43d89a78035d796c",
          "sha256": "57e6ea9d23be033ec42bfde594d1274227d59c76f3fdc280b88c50fba5edcc8c",
          "sha1": "2680efd4be7c0f393a40d0c4f2edd171326a320a",
          "md5": "f15d3f37430bfe4e950dfa8462edadb8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.0.1-sources.jar",
          "url": "core-0.0.1-sources.jar",
          "size": 118591,
          "sha512": "e4694cb8a6cd3458f7158b434ee6d2f9c0aa83edcde79659b517bf38e2a950ea7ead7dd9f32b0ee4d4732942c91edf75fd8b4095d3ef901f07198ac6833c1fe3",
          "sha256": "169a118c73fa7a505bc6e0018b93cd50f8b94219f29b110f5253e2e1a10a8457",
          "sha1": "39a4fbbcd2619413de8e792b4ce822d1ca7bc186",
          "md5": "ef30f192d408f6703618c5fc880bad1b"
        }
      ]
    }
  ]
}
